modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="btp"
version="1.2.4"
displayName="Better Tactical Presentation"
logoFile="btp.png"
credits="Powered by TACZ"
authors="Feima"
description='''
Adds a toggle key for the tilt gun mechanic in TACZ.
'''

[[dependencies.btp]]
modId="tacz"
mandatory=true
versionRange="[1.1.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.btp]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"